import { jsx as _jsx } from "react/jsx-runtime";
import React from "react";
import "./index.css";
import ReactDOM from "react-dom/client";
import App from "./App";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { AuthProvider } from "./auth/AuthProvider";
import { Provider } from "react-redux";
import { store } from "./store";
const queryClient = new QueryClient();
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsx(QueryClientProvider, { client: queryClient, children: _jsx(Provider, { store: store, children: _jsx(AuthProvider, { children: _jsx(App, {}) }) }) }) }));
