// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avinya.InsuranceCRM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108045943_campaignCustome")]
    partial class campaignCustome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Advisor", b =>
                {
                    b.Property<Guid>("AdvisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdvisorId");

                    b.ToTable("Advisors");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdvisorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ApplyToAllCustomers")
                        .HasColumnType("bit");

                    b.Property<string>("CampaignType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CampaignId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.CampaignCustomer", b =>
                {
                    b.Property<Guid>("CampaignCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CampaignCustomerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CampaignId", "CustomerId")
                        .IsUnique();

                    b.ToTable("CampaignCustomers");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.CampaignLog", b =>
                {
                    b.Property<Guid>("CampaignLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TriggerDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CampaignLogId");

                    b.HasIndex("CampaignId", "CustomerId", "TriggerDate")
                        .IsUnique();

                    b.ToTable("CampaignLogs");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.CampaignRule", b =>
                {
                    b.Property<Guid>("CampaignRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RuleEntity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RuleField")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RuleValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CampaignRuleId");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignRules");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.CampaignTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TemplateId");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignTemplates");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.ClaimHandlerMaster", b =>
                {
                    b.Property<int>("ClaimHandlerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimHandlerId"));

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ClaimHandlerId");

                    b.ToTable("ClaimHandlers");

                    b.HasData(
                        new
                        {
                            ClaimHandlerId = 1,
                            HandlerName = "Advisor",
                            IsActive = true
                        },
                        new
                        {
                            ClaimHandlerId = 2,
                            HandlerName = "ClaimOfficer",
                            IsActive = true
                        },
                        new
                        {
                            ClaimHandlerId = 3,
                            HandlerName = "Surveyor",
                            IsActive = true
                        },
                        new
                        {
                            ClaimHandlerId = 4,
                            HandlerName = "Manager",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.ClaimStageMaster", b =>
                {
                    b.Property<int>("ClaimStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimStageId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClaimStageId");

                    b.ToTable("ClaimStages");

                    b.HasData(
                        new
                        {
                            ClaimStageId = 1,
                            IsActive = true,
                            StageName = "Initiated"
                        },
                        new
                        {
                            ClaimStageId = 2,
                            IsActive = true,
                            StageName = "DocumentsPending"
                        },
                        new
                        {
                            ClaimStageId = 3,
                            IsActive = true,
                            StageName = "UnderReview"
                        },
                        new
                        {
                            ClaimStageId = 4,
                            IsActive = true,
                            StageName = "Approved"
                        },
                        new
                        {
                            ClaimStageId = 5,
                            IsActive = true,
                            StageName = "Rejected"
                        },
                        new
                        {
                            ClaimStageId = 6,
                            IsActive = true,
                            StageName = "Settled"
                        });
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.ClaimTypeMaster", b =>
                {
                    b.Property<int>("ClaimTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClaimTypeId");

                    b.ToTable("ClaimTypes");

                    b.HasData(
                        new
                        {
                            ClaimTypeId = 1,
                            IsActive = true,
                            TypeName = "Accident"
                        },
                        new
                        {
                            ClaimTypeId = 2,
                            IsActive = true,
                            TypeName = "Medical"
                        },
                        new
                        {
                            ClaimTypeId = 3,
                            IsActive = true,
                            TypeName = "Death"
                        },
                        new
                        {
                            ClaimTypeId = 4,
                            IsActive = true,
                            TypeName = "Theft"
                        },
                        new
                        {
                            ClaimTypeId = 5,
                            IsActive = true,
                            TypeName = "Fire"
                        },
                        new
                        {
                            ClaimTypeId = 6,
                            IsActive = true,
                            TypeName = "NaturalDisaster"
                        });
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdvisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Anniversary")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KYCFiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KYCStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryMobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SecondaryMobile")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PrimaryMobile")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.InsuranceClaim", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClaimHandlerId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimStageId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Documents")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TATDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ClaimId");

                    b.HasIndex("ClaimHandlerId");

                    b.HasIndex("ClaimStageId");

                    b.HasIndex("ClaimTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Insurer", b =>
                {
                    b.Property<Guid>("InsurerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsurerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortalPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortalUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InsurerId");

                    b.ToTable("Insurers");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.LeadFollowUp", b =>
                {
                    b.Property<Guid>("FollowUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("FollowUpId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadFollowUps");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.LeadSource", b =>
                {
                    b.Property<int>("LeadSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadSourceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LeadSourceId");

                    b.ToTable("LeadSources");

                    b.HasData(
                        new
                        {
                            LeadSourceId = 1,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6507),
                            DisplayOrder = 0,
                            IsActive = true,
                            SourceName = "Website"
                        },
                        new
                        {
                            LeadSourceId = 2,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6510),
                            DisplayOrder = 0,
                            IsActive = true,
                            SourceName = "Referral"
                        },
                        new
                        {
                            LeadSourceId = 3,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6511),
                            DisplayOrder = 0,
                            IsActive = true,
                            SourceName = "Agent"
                        },
                        new
                        {
                            LeadSourceId = 4,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6512),
                            DisplayOrder = 0,
                            IsActive = true,
                            SourceName = "Campaign"
                        },
                        new
                        {
                            LeadSourceId = 5,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6513),
                            DisplayOrder = 0,
                            IsActive = true,
                            SourceName = "Other"
                        });
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.LeadStatus", b =>
                {
                    b.Property<int>("LeadStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadStatusId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LeadStatusId");

                    b.ToTable("LeadStatuses");

                    b.HasData(
                        new
                        {
                            LeadStatusId = 1,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6314),
                            IsActive = true,
                            StatusName = "New"
                        },
                        new
                        {
                            LeadStatusId = 2,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6317),
                            IsActive = true,
                            StatusName = "Contacted"
                        },
                        new
                        {
                            LeadStatusId = 3,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6318),
                            IsActive = true,
                            StatusName = "Qualified"
                        },
                        new
                        {
                            LeadStatusId = 4,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6319),
                            IsActive = true,
                            StatusName = "Follow Up"
                        },
                        new
                        {
                            LeadStatusId = 5,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6321),
                            IsActive = true,
                            StatusName = "Converted"
                        },
                        new
                        {
                            LeadStatusId = 6,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6322),
                            IsActive = true,
                            StatusName = "Lost"
                        });
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.PolicyStatusMaster", b =>
                {
                    b.Property<int>("PolicyStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyStatusId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PolicyStatusId");

                    b.ToTable("PolicyStatuses");

                    b.HasData(
                        new
                        {
                            PolicyStatusId = 1,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6569),
                            IsActive = true,
                            StatusName = "Active"
                        },
                        new
                        {
                            PolicyStatusId = 2,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6571),
                            IsActive = true,
                            StatusName = "Lapsed"
                        },
                        new
                        {
                            PolicyStatusId = 3,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6572),
                            IsActive = true,
                            StatusName = "Cancelled"
                        },
                        new
                        {
                            PolicyStatusId = 4,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6573),
                            IsActive = true,
                            StatusName = "Pending"
                        });
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.PolicyTypeMaster", b =>
                {
                    b.Property<int>("PolicyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PolicyTypeId");

                    b.ToTable("PolicyTypes");

                    b.HasData(
                        new
                        {
                            PolicyTypeId = 1,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6594),
                            IsActive = true,
                            TypeName = "Fresh"
                        },
                        new
                        {
                            PolicyTypeId = 2,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6596),
                            IsActive = true,
                            TypeName = "Renewal"
                        },
                        new
                        {
                            PolicyTypeId = 3,
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6597),
                            IsActive = true,
                            TypeName = "Lost"
                        });
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommissionRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultReminderDays")
                        .HasColumnType("int");

                    b.Property<Guid>("InsurerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ProductCategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductCategoryId = 1,
                            CategoryName = "Term",
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6541),
                            IsActive = true
                        },
                        new
                        {
                            ProductCategoryId = 2,
                            CategoryName = "Health",
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6543),
                            IsActive = true
                        },
                        new
                        {
                            ProductCategoryId = 3,
                            CategoryName = "Motor",
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6544),
                            IsActive = true
                        },
                        new
                        {
                            ProductCategoryId = 4,
                            CategoryName = "Fire",
                            CreatedAt = new DateTime(2026, 1, 8, 4, 59, 43, 454, DateTimeKind.Utc).AddTicks(6546),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Renewal", b =>
                {
                    b.Property<Guid>("RenewalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReminderDatesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReminderLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RenewalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RenewalStatusId")
                        .HasColumnType("int");

                    b.HasKey("RenewalId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RenewalDate");

                    b.HasIndex("RenewalStatusId");

                    b.ToTable("Renewals");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.RenewalStatusMaster", b =>
                {
                    b.Property<int>("RenewalStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenewalStatusId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RenewalStatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("RenewalStatuses");

                    b.HasData(
                        new
                        {
                            RenewalStatusId = 1,
                            IsActive = true,
                            StatusName = "Pending"
                        },
                        new
                        {
                            RenewalStatusId = 2,
                            IsActive = true,
                            StatusName = "Renewed"
                        },
                        new
                        {
                            RenewalStatusId = 3,
                            IsActive = true,
                            StatusName = "Lost"
                        });
                });

            modelBuilder.Entity("CustomerPolicy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdvisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrokerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsurerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyDocumentRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PolicyStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PolicyTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PremiumGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PremiumNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("RenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PolicyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InsurerId");

                    b.HasIndex("PolicyStatusId");

                    b.HasIndex("PolicyTypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("CustomerPolicies");
                });

            modelBuilder.Entity("Lead", b =>
                {
                    b.Property<Guid>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdvisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConverted")
                        .HasColumnType("bit");

                    b.Property<string>("LeadNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadSourceDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LeadSourceId")
                        .HasColumnType("int");

                    b.Property<int>("LeadStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LeadId");

                    b.HasIndex("LeadSourceId");

                    b.HasIndex("LeadStatusId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.CampaignCustomer", b =>
                {
                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.Campaign", "Campaign")
                        .WithMany("CampaignCustomers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.Customer", "Customer")
                        .WithMany("CampaignCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.CampaignRule", b =>
                {
                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Rules")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.CampaignTemplate", b =>
                {
                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Templates")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.InsuranceClaim", b =>
                {
                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.ClaimHandlerMaster", "ClaimHandler")
                        .WithMany()
                        .HasForeignKey("ClaimHandlerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.ClaimStageMaster", "ClaimStage")
                        .WithMany()
                        .HasForeignKey("ClaimStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.ClaimTypeMaster", "ClaimType")
                        .WithMany()
                        .HasForeignKey("ClaimTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaimHandler");

                    b.Navigation("ClaimStage");

                    b.Navigation("ClaimType");

                    b.Navigation("Customer");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.LeadFollowUp", b =>
                {
                    b.HasOne("Lead", "Lead")
                        .WithMany("FollowUps")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Product", b =>
                {
                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Renewal", b =>
                {
                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.RenewalStatusMaster", "RenewalStatus")
                        .WithMany()
                        .HasForeignKey("RenewalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Policy");

                    b.Navigation("RenewalStatus");
                });

            modelBuilder.Entity("CustomerPolicy", b =>
                {
                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.Insurer", "Insurer")
                        .WithMany()
                        .HasForeignKey("InsurerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.PolicyStatusMaster", "PolicyStatus")
                        .WithMany()
                        .HasForeignKey("PolicyStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.PolicyTypeMaster", "PolicyType")
                        .WithMany()
                        .HasForeignKey("PolicyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Insurer");

                    b.Navigation("PolicyStatus");

                    b.Navigation("PolicyType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lead", b =>
                {
                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avinya.InsuranceCRM.Domain.Entities.LeadStatus", "LeadStatus")
                        .WithMany()
                        .HasForeignKey("LeadStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStatus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("CampaignCustomers");

                    b.Navigation("Rules");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CampaignCustomers");
                });

            modelBuilder.Entity("Avinya.InsuranceCRM.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Lead", b =>
                {
                    b.Navigation("FollowUps");
                });
#pragma warning restore 612, 618
        }
    }
}
